### ISSUE TITLE
Figure out why and how to fix heroku deploying secret keys

### ISSUE THREAD

**Issue by omarASC5** [omarASC5/Bangerz-Bots#5]
- As the issue says above, they get posted to Github and result in compromised.
- See why this happens. The file with secret keys is in a .gitignore file.
- So it should not happen.

**Comment by mihirs16** [comment]
Well, you could try using git-secrets. It helps you prevent committing any files with keys. 
But also apart from that, are u sure the name exactly matches? I guess if you are using a dotenv file then the name in .gitgnore must also be - e.g. ".env"

**Comment by omarASC5** [comment]
Oh okay, I can look into git-secrets that seems helpful.
And actually, I just heard of .env files a day or two ago so I'm using a config.py with the keys.
I will try to do the push using a .env file in .gitignore. If it doesn't work, then git-secrets.
Thanks a ton!

**Comment by omarASC5** [comment]
The .env resolved the issue @mihirs16
